encoding: UTF-8

theme: jekyll-theme-minimal

plugins:
  - jekyll-seo-tag

title: awesome-dj
description: "📄 List of reasons why django is awesome for web development"

author:
  name: Endormi
  github: endormi
  
exclude:
  - .github
  - .editorconfig
  - .gitattributes
  - boilerplate
  - AUTHORS.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - LICENSE
