theme: jekyll-theme-minimal

plugins:
  - jekyll-seo-tag
 
title: dj
description: "📄 List of reasons why django is awesome for web development"

github_username:  endormi

author:
  name: Endormi
  twitter: _endormi
