encoding: UTF-8

theme: jekyll-theme-minimal

plugins:
  - jekyll-seo-tag
 
title: dj
description: "📄 List of reasons why django is awesome for web development"

author:
  name: Endormi  
  github_username: endormi
  twitter: _endormi
