name: Feature request
description: Suggest an idea for this project
labels: 'needs-triage'
body:
  - type: markdown
    attributes:
      value: Thank you for opening a feature request!
  - type: textarea
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the request.
    validations:
      required: false
