name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 * * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has gone stale. Remove the label if this still needs to be worked on (typically stale issues will be closed).'
        stale-pr-message: 'This pull request has gone stale. Remove the label if this still needs to be worked on (typically stale PRs will be closed).'
        stale-issue-label: 'stale-issue'
        stale-pr-label: 'stale-pr'
